sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '10'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: Obx7ujsi5TOh0kAdxrCIj2osZF5efUsbDtEFx/fN80VyGQbMd8UHb2GCSutRwttlD0CSlU1AIKiqLb1jPXgAA5WnpVEzWuB32lDJJQcuISWB799PQiO58aHT/XQDPVwJbDJZPCBPTfJPb1Vpg1gk/m+pWhWY2OWXlwqhL5YwZK7iB7OOoY7bGIAmhEg58QndRu7K9sfVDUzNTW1ikbCGvdZ9Sle5oVaEh8ucv5kgwFq+P2wRp3D9k03lBhxFsg9iOHDly9sZewJU+uNHHFaGQjDB5RzQtwf2jmbg389IBOG7qoFTpBbnuZcMCeqY9hq2ZMJHqHAr3VdPWWmgpbFY5G8oyHIdjnQI2I6sDTfNjEYfeKou4LyNNEz25PvwgJ7ICa2CPkSzCCqQFWTk4Ww6N8zYyVZ/Ryl2vD8qasDGiVx+//rPluhItO0DnWNz8IQI8+PCib8se0MGGqxqhbtvBTZdpLcWN/5anXjqDCQMFRlTgAeednqeRhPvDnXEIEh7El86D5TehWnpX3Ws0goyX9e3UORnmKMKivtkCLRZsA/t4MhP/lxZiIoPpC5Yl/64X8F3M2bK9wPVyPLwfsiy/T7tjyDPTIA8ZWSv7k/YlQcnrS5qXTozzoqrbsbo75WLea/6Z70qcAWdKtqUkl6rfrm8W7iCAo6s5UTbIXbx6g8=
